# This is a world configuration file for Paper.
# This file may start empty but can be filled with settings to override ones in the config/paper-world-defaults.yml
# 
# World: SkyBlock-V1 (minecraft:skyblock-v1)

_version: 30
